# Config file for automatic testing at travis-ci.org

language: python
sudo: false

python:
    - 3.5
    - 3.6
    - 3.7

before_install:
    - wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda info -a

install:
    - if [[ $TRAVIS_PYTHON_VERSION != 3.7 ]]; then conda create -q -n test_env python=$TRAVIS_PYTHON_VERSION ; fi
    - if [[ $TRAVIS_PYTHON_VERSION == 3.7 ]]; then conda create -q -n test_env python=3.7                    ; fi
    - source activate test_env
    - conda install numpy scipy sqlalchemy setuptools pytest coverage
    - pip install codecov
    - cd python
    - python setup.py install

script:
    - cd tests
    - coverage run --source=xraydb -m pytest
    - coverage report -m

after_success:
    - codecov
